### ISSUE TITLE
`brownie compile` doesn't procude any artifacts for `token` template

### ISSUE THREAD

**Issue by max-block** [iamdefinitelyahuman/brownie#477] opened 2020-05-03 06:49 UTC
### Environment information

* `brownie` Version: v1.8.1
* `ganache-cli` Version: v6.9.1
* `solc` -- There is nothing in installation info about solc dependecy. I've installed it like `brew install solidity`, solc --version = 0.6.6
* Python Version: 3.8.1
* OS: osx 10.15.4

### What was wrong?
`brownie compile` doesn't procude any artifacts. Here are console logs how I did it:

```
max@mbp ~ $ pipx install eth-brownie
  installed package eth-brownie 1.8.1, Python 3.8.1
  These apps are now globally available
    - brownie
done! ✨ 🌟 ✨

max@mbp _tmp $ brownie bake token
Brownie v1.8.1 - Python development framework for Ethereum

Downloading from https://github.com/brownie-mix/token-mix/archive/master.zip...
4.45kiB [00:00, 1.71MiB/s]
SUCCESS: Brownie mix 'token' has been initiated at /Users/max/p/_tmp/token

max@mbp _tmp $ cd token/
max@mbp token $ brownie compile
Brownie v1.8.1 - Python development framework for Ethereum

Project has been compiled. Build artifacts saved at /Users/max/p/_tmp/token/build/contracts

max@mbp token $ tree .
.
├── LICENSE
├── README.md
├── build
│   ├── contracts
│   ├── deployments
│   └── interfaces
├── contracts
│   ├── SafeMath.sol
│   └── Token.sol
├── interfaces
├── reports
├── scripts
│   └── token.py
└── tests
    ├── conftest.py
    ├── test_approve_transferFrom.py
    └── test_transfer.py

9 directories, 8 files
```

**Comment by iamdefinitelyahuman** [comment] 2020-05-03 07:18
Thanks for opening an issue!

The problem is a bug related to `_tmp` in the install path.  If you move the project to another location so that none of the directory names in the path have a leading underscore, the issue should be fixed.

I'll fix that right away and have a patch release out later today.

**Closed** 2020-05-03 09:07 UTC
Labels: bug
