### ISSUE TITLE
Support interactive debugging of `brownie run`

### ISSUE THREAD

**Issue by WyseNynja** [iamdefinitelyahuman/brownie#538] opened 2020-05-22 21:19 UTC
### Overview

I'm writing some run scripts and they have some bugs. It would be really handy to be able to do `brownie run -I ...` just like I can do `brownie test -I`

**Comment by iamdefinitelyahuman** [comment] 2020-05-23 07:03
Duplicate of #520

**Closed by iamdefinitelyahuman** 2020-05-23 07:03 UTC
